version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=thespot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  api:
    image: thespot/api 
    build:
      context: api
    ports:
      - '8080:8080'
    command: "tail -f /dev/null"

  client:
    image: thespot/client
    build:
      context: client
    ports:
      - '8081:8081'
    command: "tail -f /dev/null"
      
volumes:
  db:
    driver: local